### ISSUE TITLE
Readme Updates Needed [EddieHub Reviewer]

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [uzair-ali10/uzair-ali10#1]
- Make Gmail, Instagram, & LinkedIn button on the same line (I have raised an issue for the same)
- Remove VS code from the languages and tools section
- Remove GitHub from Version Control System and DevOps section as you are on the same platform
- Remove My walkline stats as that should be reflected by your work
- Put Github stats card and Languages card on the same line
- If you want you can remove the profile visit section as well.

**Comment by uzair-ali10** [comment]
Thanks for the correction, Made the necessary changes
